# Generated by Django 5.0.6 on 2024-08-27 06:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_answer_unique_id_answerdetail_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='answerdetail',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='option',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='answerdetail',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='option',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
